env:
  global:
    - CC_TEST_REPORTER_ID=1ab5ea0a8b53d6cc573cab7cbe2f9c29c33ee4fee596d8880626d9a2e44e1a10
language: ruby
rvm:
  - 2.5.3
before_install: gem install bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT